version: '2.3'
services:
  gdl:
    build: .
    command: /bin/bash
    environment:
      - DISPLAY=${HOSTNAME}:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../pro:/home/gdluser/pro
      - ../Resources:/home/gdluser/Resources
      - ../EMsoftData:/home/gdluser/data
    network_mode: "host"
